import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#002109",
        "surface-container-low": "#f2f4f6",
        "inverse-primary": "#3de273",
        "on-error-container": "#93000a",
        "primary-container": "#25d366",
        "surface-tint": "#006d2f",
        "on-primary-container": "#005523",
        "primary-fixed": "#66ff8e",
        "on-tertiary-container": "#004699",
        "primary": "#006d2f",
        "secondary": "#565e74",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed-dim": "#3de273",
        "tertiary-fixed-dim": "#adc6ff",
        "on-tertiary-fixed-variant": "#004395",
        "on-surface-variant": "#3c4a3d",
        "on-secondary-fixed-variant": "#3f465c",
        "inverse-on-surface": "#eff1f3",
        "tertiary": "#005ac2",
        "tertiary-container": "#97b8ff",
        "secondary-fixed": "#dae2fd",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#005322",
        "secondary-fixed-dim": "#bec6e0",
        "on-error": "#ffffff",
        "surface-bright": "#f7f9fb",
        "surface-container": "#eceef0",
        "outline-variant": "#bbcbb9",
        "inverse-surface": "#2d3133",
        "background": "#f7f9fb",
        "surface": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e",
        "on-secondary": "#ffffff",
        "outline": "#6c7b6b",
        "secondary-container": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1e",
        "surface-dim": "#d8dadc",
        "surface-variant": "#e0e3e5",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#d8e2ff",
        "on-tertiary-fixed": "#001a42",
        "on-secondary-container": "#5c647a",
        "on-secondary-fixed": "#131b2e",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "32px",
        "margin-desktop": "40px",
        "stack-md": "16px",
        "base": "4px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "container-max": "1440px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "code": ["Geist", "monospace"],
        "label-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "code": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
};
export default config;
